import Head from 'next/head'
import Header from './components/Header'
import 'bootstrap/dist/css/bootstrap.min.css';
import Projects from './components/Projects';
import Footer from './components/Footer';


export default function Home() {
  return (
    <div style={{padding: "10% 20% 10% 20%"}}>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Projects/>
      <Footer/>
    </div>
  )
}
