import Head from 'next/head'
import Header from './components/Header'
import Footer from './components/Footer';
import Carousel from './components/Carousel';


export default function Home() {
  return (
    <div style={{padding: "10% 20% 10% 20%"}}>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Carousel style={{heigh: "400px"}} />
      <Footer/>
    </div>
  )
}
